<?php
require_once __DIR__ . '/../api/config.php';
session_start();
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['password'])) {
    if ($_POST['password'] === ADMIN_PASSWORD) $_SESSION['admin'] = true;
    else $error = 'Wrong password';
}
if (isset($_POST['logout'])) { session_destroy(); header('Location: index.php'); exit; }
if (!isset($_SESSION['admin'])): ?>
<!DOCTYPE html><html><head><title>Admin Login</title><style>body{font-family:Arial;background:#0b1020;color:#fff;display:flex;align-items:center;justify-content:center;height:100vh;margin:0}.box{background:#111827;padding:30px;border-radius:14px;border:1px solid #1f2937;min-width:320px}input{width:100%;padding:12px;background:#0f172a;border:1px solid #334155;color:#fff;border-radius:8px;box-sizing:border-box;margin:10px 0}.btn{width:100%;padding:12px;background:#ef4444;color:#fff;border:none;border-radius:8px;font-weight:700;cursor:pointer}.e{color:#fca5a5}</style></head><body><div class="box"><h2>🔐 Devil AI Admin</h2><?php if(isset($error)) echo '<p class="e">'.$error.'</p>'; ?><form method="post"><input type="password" name="password" placeholder="Admin password" required><button class="btn">Login</button></form></div></body></html><?php exit; endif;
$db = getDB();
$totalKeys = $db->query("SELECT COUNT(*) FROM api_keys")->fetchColumn();
$activeKeys = $db->query("SELECT COUNT(*) FROM api_keys WHERE is_active = 1")->fetchColumn();
$totalRevenue = $db->query("SELECT COALESCE(SUM(subscription_amount_inr),0) FROM api_keys WHERE is_active = 1")->fetchColumn();
$totalReqs = $db->query("SELECT COALESCE(SUM(total_requests),0) FROM api_keys")->fetchColumn();
$clients = $db->query("SELECT * FROM api_keys ORDER BY created_at DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html><html><head><title>Admin Dashboard</title><style>body{font-family:Arial;background:#0b1020;color:#e5e7eb;margin:0}.nav{background:#111827;padding:16px 24px;display:flex;justify-content:space-between;align-items:center}.nav a{color:#cbd5e1;text-decoration:none;margin-left:14px}.wrap{padding:24px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:#111827;border:1px solid #1f2937;border-radius:14px;padding:20px}.n{font-size:30px;font-weight:800;color:#fff}.l{color:#94a3b8;font-size:13px;margin-top:6px}table{width:100%;border-collapse:collapse;background:#111827;border:1px solid #1f2937;border-radius:14px;overflow:hidden;margin-top:18px}th,td{padding:12px;border-bottom:1px solid #1f2937;text-align:left;font-size:13px}.tag{padding:3px 8px;border-radius:6px;font-size:11px}.on{background:#123b24;color:#86efac}.off{background:#3b1219;color:#fca5a5}@media(max-width:900px){.stats{grid-template-columns:1fr 1fr}}</style></head><body><div class="nav"><div><strong>😈 Devil AI Admin</strong></div><div><a href="keys.php">Keys</a><a href="../docs/">Docs</a><form method="post" style="display:inline"><button name="logout" style="background:none;border:none;color:#fff;cursor:pointer;margin-left:14px">Logout</button></form></div></div><div class="wrap"><div class="stats"><div class="card"><div class="n"><?= $totalKeys ?></div><div class="l">Total Keys</div></div><div class="card"><div class="n"><?= $activeKeys ?></div><div class="l">Active Keys</div></div><div class="card"><div class="n">₹<?= number_format((float)$totalRevenue,2) ?></div><div class="l">Active Revenue</div></div><div class="card"><div class="n"><?= number_format((int)$totalReqs) ?></div><div class="l">Total Requests</div></div></div><table><tr><th>App</th><th>Client</th><th>Email</th><th>Plan</th><th>Amount</th><th>Speed</th><th>RPM</th><th>Daily</th><th>Expiry</th><th>Status</th></tr><?php foreach($clients as $c): ?><tr><td><?= htmlspecialchars($c['app_name']) ?></td><td><?= htmlspecialchars($c['client_name']) ?></td><td><?= htmlspecialchars($c['client_email']) ?></td><td><?= htmlspecialchars($c['plan_name']) ?></td><td>₹<?= number_format((float)$c['subscription_amount_inr'],2) ?></td><td><?= htmlspecialchars($c['speed_tier']) ?></td><td><?= (int)$c['rpm_limit'] ?></td><td><?= (int)$c['limit_per_day'] ?></td><td><?= htmlspecialchars((string)$c['expires_at']) ?></td><td><span class="tag <?= (int)$c['is_active']===1?'on':'off' ?>"><?= (int)$c['is_active']===1?'Active':'Disabled' ?></span></td></tr><?php endforeach; ?></table></div></body></html>
